### ISSUE TITLE
Add REPL feature

### ISSUE THREAD

**Issue by webappzero** [clojurecademy/clojurecademy#1]
Congrats on launching Clojurecademy with so many great features! One thing I miss when working on the site is convenient access to a REPL. Sites like [repl.it](https://repl.it) offer a rich Clojure REPL experience online.

Are you interested in adding a REPL?

**Comment by ertugrulcetin** [comment]
@webappzero thank you for reaching out! Yes, actually I'm considering to add this feature in near future!

**Comment by ertugrulcetin** [comment]
@webappzero about REPL feature, should it be a separate process I mean you can test your code getting feedback not passing instructions or it should work like it's now but with a REPL approach?

**Comment by webappzero** [comment]
I'm not certain whether the REPL should be in the same process or not, but probably so. 

I was glad to see in your project rationale a goal to make it easier for newcomers to get started with Clojure, shielding them from complicated local setup.  When I was working on the bowling kata on a hotel computer (while traveling last weekend), I used repl.it to solve the problem so that I could use a repl to play around with the data and perform small tests, just like I would on my dev laptop at home. Then I copied that code into clojurecademy.com to complete the kata tests.

Trying to solve that problem on clojurecademy with only the feedback built into the kata was like flying blind because I couldn't experiment to produce my own relevant feedback by playing with data etc. With repl.it, being able to run my code and then have the names/values in the repl's memory was a powerful convenience which saved lots of copy and pasting to recreate the namespace's global state etc. 

If we could match that experience, I think we'd better showcase and provide the interactive nature of Clojure, though I imagine it's difficult to do online.

I'm not sure how best to integrate the REPL experience with the test feedback experience. I guess the two obvious options are to unify or separate those experiences. Starting with the easiest option seems like the best option for now.

Also, thanks for making this open source! I look forward to helping out and learning along the way.

Are there any significant technical challenges that need researching with this feature?

**Comment by ertugrulcetin** [comment]
Thank you for your feedback! I think we need to think about the implementation a bit more and I will need to ask this to the Clojure community to get others ideas(that could be helpful).

Implementing this feature would be very straightforward, it should not take so much time I guess.

**Comment by ertugrulcetin** [comment]
@webappzero I've added REPL feature, could you check it and provide some feedback please?

**Comment by webappzero** [comment]
I can enter expressions in the code area and click the blue REPL button to see the resulting values in the console area. **That's nice!**

One suggestion, I think it would be cool to be able to _interact with a repl prompt in that console area._ That isn't a massive win over what exists now. However, my brain expected to be able to click in the console area and start typing, so I wasn't sure at first if the interface was working correctly.

**Comment by ertugrulcetin** [comment]
@webappzero Thank you for your feedback! About that repl prompt, it's little bit complicated with current design but it makes sense. Maybe I can implement that after couple of iterations. 

Is current REPL feature enough right now, can I close issue?
