### ISSUE TITLE
It seems that the site is not live anymore??

### ISSUE THREAD

**Issue by touxstone** [clojurecademy/clojurecademy#8]
Is it me or the [site](https://clojurecademy.com) is not live anymore?. I only got `ERROR 502`

**Comment by zelark** [comment]
Not only you, I got the same.

**Comment by ertugrulcetin** [comment]
Yeah I had to shutdown for a while, I'll make it online asap

**Comment by neominik** [comment]
Any updates on this?

**Comment by ChrisLane** [comment]
![](https://i.imgur.com/FuENSuo.png)
:disappointed:

**Comment by ertugrulcetin** [comment]
It will become available ASAP (it's funded)...stay tuned guys :)

**Comment by ertugrulcetin** [comment]
It's online again :) @touxstone @zelark @neominik @ChrisLane
